default:
  adapter: mysql2
  uri: <%= ENV['DATABASE_URL'] %>

development:
  adapter: mysql2
  uri: <%= ENV['DATABASE_URL'] %>

test:
  adapter: mysql2
  uri: <%= ENV['DATABASE_URL'] %>

production:
  adapter: mysql2
  uri: <%= ENV['DATABASE_URL'] %>
