default:
  adapter: mysql2
  host: davidkingjr.com
  port: 3306
  database: fcgp
  username: fcgp_user
  password: apg2nsas

development:
  adapter: mysql2
  host: davidkingjr.com
  port: 3306
  database: fcgp
  username: fcgp_user
  password: apg2nsas

test:
  adapter: mysql2
  uri: <%= ENV['DATABASE_URL'] %>

production:
  adapter: mysql2
  uri: <%= ENV['DATABASE_URL'] %>
